spring:
  application:
    name: LibraryHub

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whatsapp
    username: root
    password: "Kirti@1304"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081